logging:
  level: INFO
  loggers:
    dlopezgarsco: DEBUG

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:gila;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
  user: root
  password: root
  minSize: 1
  maxSize: 1
  initialSize: 1